export type Login = {
  password: string;
  isOnline: boolean;
};

export type ObjectMessage =
  | Auth
  | ResultAuth
  | UpdateWinners
  | CreateRoom
  | InviteRoom
  | CreateGame
  | UpdateRoom
  | AddShips
  | StartGame
  | Attack
  | AttackFeedback
  | RandomAttack
  | PlayerTurn
  | FinishGame;

export type MessagesTypes =
  | 'reg'
  | 'update_winners'
  | 'create_room'
  | 'add_user_to_room'
  | 'create_game'
  | 'update_room'
  | 'add_ships'
  | 'start_game'
  | 'attack'
  | 'randomAttack'
  | 'turn'
  | 'finish';

export type RawMessage = {
  type: MessagesTypes;
  data: string;
  id: 0;
};
export interface BaseMessage {
  type: MessagesTypes;
  data: object | string | Array<object>;
  id: 0;
}

export interface Auth extends BaseMessage {
  type: 'reg';
  data: {
    name: string;
    password: string;
  };
}
export interface ResultAuth extends BaseMessage {
  type: 'reg';
  data: {
    name: string;
    index: number | string;
    error: boolean;
    errorText: string;
  };
}
export type Winner = {
  name: string;
  wins: number;
};

export interface UpdateWinners extends BaseMessage {
  type: 'update_winners';
  data: Winner[];
}
export interface CreateRoom extends BaseMessage {
  type: 'create_room';
  data: '';
}
export interface InviteRoom extends BaseMessage {
  type: 'add_user_to_room';
  data: {
    indexRoom: number | string;
  };
}
export interface CreateGame extends BaseMessage {
  type: 'create_game'; //send for both players in the room, after they are connected to the room
  data: {
    idGame: number | string;
    idPlayer:
      | number
      | string /* generated by server id for player in the game session, not enemy (unique id for every player) */;
  };
}

export type RoomUser = {
  name: string;
  index: number | string;
};
export type Room = {
  roomId: number | string;
  roomUsers: RoomUser[];
};

export interface UpdateRoom extends BaseMessage {
  type: 'update_room';
  data: Room[];
}

export type Position = {
  x: number;
  y: number;
};

export type Ship = {
  position: Position;
  direction: boolean;
  length: number;
  type: 'small' | 'medium' | 'large' | 'huge';
};

export type CoordinateState = {
  coordinate: string;
  breaked: boolean;
};
export type ShipPosition = {
  isKilled: boolean;
  coordinates: CoordinateState[];
};
export type UserShips = {
  userId: string | number;
  positions: ShipPosition[];
};

export type GameArea = Array<{
  username: string;
  indexPlayer: string | number;
  ships: Ship[];
}>;

export interface AddShips extends BaseMessage {
  type: 'add_ships';
  data: {
    gameId: number | string;
    ships: Ship[];
    indexPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
}
export interface StartGame extends BaseMessage {
  type: 'start_game';
  data: {
    ships: Ship[] /* player's ships, not enemy's */;
    currentPlayerIndex:
      | number
      | string /* id of the player in the current game session, who have sent his ships */;
  };
}
export interface Attack extends BaseMessage {
  type: 'attack';
  data: {
    gameId: number | string;
    x: number;
    y: number;
    indexPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
}
export type FeedbackStaus = 'miss' | 'killed' | 'shot';
export interface AttackFeedback extends BaseMessage {
  type: 'attack';
  data: {
    position: Position;
    currentPlayer:
      | number
      | string /* id of the player in the current game session */;
    status: FeedbackStaus;
  };
}
export interface RandomAttack extends BaseMessage {
  type: 'randomAttack';
  data: {
    gameId: number | string;
    indexPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
}

export interface PlayerTurn extends BaseMessage {
  type: 'turn';
  data: {
    currentPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
}
export interface FinishGame extends BaseMessage {
  type: 'finish';
  data: {
    winPlayer:
      | number
      | string /* id of the player in the current game session */;
  };
}

export type IsShooting = {
  indexPlayer: string | number;
  thutly: boolean;
};
